// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Script Commands
 * Place the definition of custom script commands in this file.
 * Format:
 *	BUILDIN_DEF(command_name,"parameters"),
 **/

//BUILDIN_DEF(example,""),
	BUILDIN_DEF(bg_move_queue, "ss"),
	BUILDIN_DEF(viewpointmap,"siiiii"),
	BUILDIN_DEF(storeitem2,"viiiiiiii?"),
	BUILDIN_DEF(checkspace,"viiiiiiii"),
	BUILDIN_DEF(itembound2,"viiiiiiii?"),
	BUILDIN_DEF(storeitem,"vi?"),
	BUILDIN_DEF(itembound,"vi?"),
	BUILDIN_DEF(countstorageitem,"iiiiiiiii?"),
	BUILDIN_DEF(stor2inv,"iiiiiiiii?"),
	BUILDIN_DEF(inv2stor,"iiiiiiiii?"),
	BUILDIN_DEF(bgstart,""),
	BUILDIN_DEF(bgend,""),
	BUILDIN_DEF(bgcheck,""),
	BUILDIN_DEF(bg_flagemblem,"i"),	// Flag Emblem
	BUILDIN_DEF(pcblock,"ii?"),
	BUILDIN_DEF(unitisfighting,"i"),
	BUILDIN_DEF(bg_team_reveal,"i"),
	BUILDIN_DEF(bg_getitem,"iii"),
	BUILDIN_DEF(bg_reward,"iiiiisii"),
	BUILDIN_DEF(bg_reward_all,"siiiii"),
	BUILDIN_DEF(bgannounce,"s?????"),
	BUILDIN_DEF(bg_logincount,""),
	BUILDIN_DEF(bg_clean,"i"),
	BUILDIN_DEF(bg_joinbg, "s"),
	BUILDIN_DEF(bg_current_mode, ""),
	BUILDIN_DEF(bg_set_current_mode, "i"),
	BUILDIN_DEF(bg_modeselection, ""),
	BUILDIN_DEF(bg_leavebg, "s"),
	BUILDIN_DEF(bg_premature_end, "i"),
